name: Build Typst document
on: 
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: prep typst
        uses: typst-community/setup-typst@v3
      - run: typst compile ra-template.typ ra-template.pdf

      - name: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ra-template.pdf
